### ISSUE TITLE
Support for InfluxDB 0.9.2

### ISSUE THREAD

**Issue by skynet** [influxdb/influxdb-php#13]
There might be [some breaking changes in 0.9.2](https://github.com/influxdb/influxdb/blob/master/CHANGELOG.md#v092-2015-07-24), particularly with inserting integer values.

https://github.com/influxdb/influxdb/issues/3606

Is the library updated to support these changes in 0.9.2 (and soon 0.9.3)?

**Comment by thecodeassassin** [comment]
We will update the library for 0.9.3 as that one contains the breaking change.

**Comment by skynet** [comment]
0.9.3 is out.

**Comment by thecodeassassin** [comment]
0.9.3 is not released as stable yet. We are actively working on the 0.9.3 upgrade but somehow our values are not ending up in InfluxDB. We don't do half work or release non-functional code so it's going to take a bit more time. Please bear with us.

**Comment by thecodeassassin** [comment]
1.0.2 is released; which has support for 0.9.3 rc2

**Comment by thecodeassassin** [comment]
@skynet i changed the version to 1.1.0 since i think breaking changes should be tagged as a minor.

**Comment by skynet** [comment]
:+1: wow, this is great news. Finally a stable release. I hope that InfluxDB itself would become stable one day. Otherwise it will be soon known as "BreakingDB". 

Going to migrate our code to the new library and I'll let you know if any problems.

**Comment by thecodeassassin** [comment]
Thanks @skynet ! Let us know when you run into any issue. I myself also have issues with InfluxDB, we had to pull it from production because of a lot of missing data and we use that data for invoicing. We are still using openTSBD right now which is also why we are a little behind with development, we do it now purely for the community not for our own goals (of having a stable Time Series Database).
