### ISSUE TITLE
Should this package compatible with PHP 5.3?

### ISSUE THREAD

**Issue by CentaurWarchief** [influxdb/influxdb-php#8]
Why? PHP 5.3 is not supported anymore since **11 months ago**. So why should we? http://php.net/eol.php

I really think we should move on. We're in the imminence of PHP 7 and at the same time supporting old branches :(.

**Comment by thecodeassassin** [comment]
I fully agree with you!, sadly our production stack still relies on 5.3. We have debated on this many times and  decided to add support for 5.3 in the end. 

Makes me sad for a couple of reasons:

- Not being able to use a more recent and supported version of some dependencies like guzzle
- Not being able to use short array syntax
- etcetc

I will start an internal discussion again to see if we can remove support for PHP 5.3 a.s.a.p. Because it is redundant.

**Comment by CentaurWarchief** [comment]
Well, you can end with PHP 5.3 support with a final release, a tag. Everything afterwards will not compatible with 5.3 or neither 5.4 (I must say). 

I think this fixes the problem and promotes the compatibility. What do you think?

**Comment by thecodeassassin** [comment]
I am creating a 1.0.0 branch that only supports php 5.5+ and supports UDP

**Comment by CentaurWarchief** [comment]
Whoa. So we can close this issue?

**Comment by thecodeassassin** [comment]
Once it's released, sure :) Do you also want to help with unit tests/functional tests?

**Comment by thecodeassassin** [comment]
1.0.0 doesn't support PHP < 5.5

**Comment by CentaurWarchief** [comment]
@thecodeassassin Great work!
